version: "2.6"
services:
  pg:
    image: postgres:13-alpine
    container_name: pg
    restart: always
    ports:
      - 5200:5432
    volumes:
      - postdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postdb
      - POSTGRES_PASSWORD=test_tcit
      - POSTGRES_USER=test_tcit
volumes:
  postdb:
    driver: local
